version: '3'
services:
  my-app:
    build:
      context: .
    ports:
      - "8080:80"
    restart: always 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MySQLConfig__dbhost=mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin